# Project information
site_name: 'مستندات نرم افزار آزمایشی '
site_description: 'مستندات REST API آزمایشی'
site_author: 'mohammadreza berneti'
site_url: 'http://berneti.ir'

# Repository
repo_name: 'mkdocs-rtl'
repo_url: 'https://github.com/mberneti/mkdocs-rtl'

# Copyright
copyright: 'Copyright &copy; 2016 - 2017 Mohammadreza Berneti'

docs_dir: 'pages'
site_dir: 'docs'
# base_url: 'bb'

nav:
    - مقدمه: index.md
    - سرویس‌ها:
      - 'احراز هویت': 'accounts-services.md'

# Documentation and theme
theme:
    name: 'material'
    custom_dir: 'theme'
extra_css:
  - 'custom-docs.css'

# Options
# extra:
#   logo: 'images/logo.svg'
#   palette:
#     primary: 'indigo'
#     accent: 'indigo'
#   font:
#     text: 'Roboto'
#     code: 'Roboto Mono'
#   social:
#     - type: 'github'
#       link: 'https://github.com/john-doe'
#     - type: 'twitter'
#       link: 'https://twitter.com/john-doe'
#     - type: 'linkedin'
#       link: 'https://linkedin.com/in/john-doe'

# Google Analytics
# google_analytics:
#   - 'UA-XXXXXXXX-X'
#   - 'auto'

# Extensions
markdown_extensions:
  - admonition
#  - codehilite(guess_lang=false)
#  - toc(permalink=⚓)
